language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

dist: xenial

install:
    - pip install -U pip
    - pip install jaxlib
    - pip install jax
    - pip install .[examples,test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - stage: lint / docs
          before_install: pip install .[doc]
          python: 3.6
          script:
            - make lint
            - make docs
            - make doctest
        - stage: unit
          name: "unit tests"
          python: 3.6
          script:
              - pytest -vs -k "not test_example" --deselect test/contrib/test_distributions_contrib.py --durations=100
              - JAX_ENABLE_x64=1 pytest -vs test/test_mcmc.py
              - XLA_FLAGS="--xla_force_host_platform_device_count=2" pytest -vs test/test_mcmc.py -k pmap
              - XLA_FLAGS="--xla_force_host_platform_device_count=2" pytest -vs test/test_mcmc_interface.py -k chain
        - name: "examples"
          python: 3.6
          script:
              - pytest -vs -k test_example
              - XLA_FLAGS="--xla_force_host_platform_device_count=2" pytest -vs -k test_example
