language: python

os: linux

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

dist: xenial

install:
    - pip install -U pip
    # Keep track of pyro-api master branch
    - pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip
    - pip install https://github.com/pyro-ppl/funsor/archive/master.zip
    - pip install jaxlib
    - pip install jax>=0.1.70
    - pip install .[examples,test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - stage: lint / docs
          before_install: pip install .[doc]
          python: 3.6
          script:
            - make lint
            - make docs
            - make doctest
        - stage: unit
          name: "unit tests"
          python: 3.6
          script:
              - pytest -vs -k "not test_example" --deselect test/contrib/test_distributions_contrib.py --durations=100
              - JAX_ENABLE_X64=1 pytest -vs test/test_mcmc.py -k x64
              - XLA_FLAGS="--xla_force_host_platform_device_count=2" pytest -vs test/test_mcmc.py -k \
                  "chain or pmap or vmap"
        - name: "examples"
          python: 3.6
          script:
              - pytest -vs -k test_example
              - XLA_FLAGS="--xla_force_host_platform_device_count=2" pytest -vs -k test_example
